name: Validate
on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.17.5'
      - run: rustup target add wasm32-unknown-unknown

      - name: Format
        run: cargo fmt --all --check

      - name: Lint
        run: |
          cargo clippy -p frontend --target wasm32-unknown-unknown
          cargo clippy --workspace --exclude frontend

      - name: Check
        env:
          API_URL: http://localhost:8080 # to allow cargo check to run
        run: |
          cargo check -p frontend --target wasm32-unknown-unknown
          cargo check --workspace --exclude frontend
